kind: ConfigMap
apiVersion: v1
metadata:
  name: smi-config-mapper
  namespace: dataspace
data: 
  config.ini: |
    [NewsCollector]
    mode = auto
    semaphore = 4

    [NewsParser]
    semaphore = 4

    [Arango]
    arangoURL = http://158.160.42.54:8529
    username = root
    password = infoprofile
    db_name = infoprofile
    collection_channels_name = tmp_channels
    collection_proxy_name = smi_proxy
    
    [Sentry]
    dsn = https://b74c52888ac72c34f4ef141370c53397@o4506745820348416.ingest.sentry.io/4506752175374336

